[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
ttc-methods = { path = "../methods" }
risc0-zkvm = { version = "0.18.0" }
serde = "1.0"
hex = "0.4"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]
